name:                prob-school
version:             0.1.0.0
github:              "ccshan/prob-school"
license:             MIT
author:              "Chung-chieh Shan"
maintainer:          "ccshan@indiana.edu"
copyright:           "2019 Chung-chieh Shan"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/ccshan/prob-school#readme>

dependencies:
- base >= 4.7 && < 5
- Chart
- Chart-diagrams
- array
- bytestring
- cassava
- colour
- containers
- data-default
- erf
- lens
- logfloat
- pretty-show
- random
- transformers
- vector

library:
  source-dirs: src
